// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Audio: typeof import('./src/components/atoms/Audio.vue')['default']
    Button: typeof import('./src/components/atoms/Button.vue')['default']
    DropdownList: typeof import('./src/components/atoms/DropdownList.vue')['default']
    Form: typeof import('./src/components/atoms/Form.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Input: typeof import('./src/components/atoms/Input.vue')['default']
    Navbar: typeof import('./src/components/layouts/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoInput: typeof import('./src/components/todo/TodoInput.vue')['default']
    TodoListItem: typeof import('./src/components/todo/TodoListItem.vue')['default']
    TodoTypeSwitch: typeof import('./src/components/todo/TodoTypeSwitch.vue')['default']
  }
}
